import "server-only";

import { getOrgRetailMarginPct } from "@/lib/pricing/org-retail-margin";
import { requireManagerContext } from "@/lib/server/require-manager";
import { requireOrgContext } from "@/lib/server/org-context";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import { retailPriceFromCost } from "@/lib/utils/calculations";
import { upsertRetailPrice } from "@/lib/inventory/product-prices";

export type ApplyMissingRetailPricesResult =
  | { ok: true; updated: number; marginPct: number }
  | { ok: false; message: string };

/** Set retail from cost × org margin for products with no retail price (cost > 0). */
export async function applyMissingRetailPricesCore(
  outletId?: string | null
): Promise<ApplyMissingRetailPricesResult> {
  try {
    await requireManagerContext();
    const ctx = await requireOrgContext();
    const supabase = await createServerSupabaseClient();
    const marginPct = await getOrgRetailMarginPct();

    const { data: products, error: pErr } = await supabase
      .from("products")
      .select("id")
      .eq("organization_id", ctx.organizationId)
      .eq("is_active", true);
    if (pErr) return { ok: false, message: pErr.message };
    if (!products?.length) return { ok: true, updated: 0, marginPct };

    const ids = products.map((p) => p.id);
    const { data: priceRows } = await supabase
      .from("product_prices")
      .select("product_id")
      .in("product_id", ids)
      .eq("price_type", "retail")
      .is("effective_to", null);
    const hasRetail = new Set(
      ((priceRows ?? []) as { product_id: string }[]).map((r) => r.product_id)
    );

    let stockQuery = supabase
      .from("stock")
      .select("product_id, cost_price")
      .eq("organization_id", ctx.organizationId);
    const costOutlet = outletId ?? ctx.outletId;
    if (costOutlet) {
      stockQuery = stockQuery.eq("outlet_id", costOutlet);
    }
    const { data: stockRows, error: sErr } = await stockQuery;
    if (sErr) return { ok: false, message: sErr.message };

    const maxCostByProduct = new Map<string, number>();
    for (const s of stockRows ?? []) {
      const cost = Number(s.cost_price);
      const prev = maxCostByProduct.get(s.product_id) ?? 0;
      if (cost > prev) maxCostByProduct.set(s.product_id, cost);
    }

    let updated = 0;
    for (const p of products) {
      if (hasRetail.has(p.id)) continue;
      const cost = maxCostByProduct.get(p.id) ?? 0;
      if (cost <= 0) continue;
      const retail = retailPriceFromCost(cost, marginPct);
      await upsertRetailPrice(supabase, p.id, retail, { autoGenerated: true });
      const { ensureBaseProductUnit } = await import(
        "@/lib/actions/product-units"
      );
      const { data: prod } = await supabase
        .from("products")
        .select("unit")
        .eq("id", p.id)
        .maybeSingle();
      await ensureBaseProductUnit(
        supabase,
        p.id,
        prod?.unit ?? "pcs",
        retail,
        retail
      );
      updated += 1;
    }

    return { ok: true, updated, marginPct };
  } catch (e) {
    return {
      ok: false,
      message: e instanceof Error ? e.message : "Apply retail prices failed",
    };
  }
}
