import "server-only";

import { syncBaseUnitRetailPrice } from "@/lib/actions/product-units";
import { createServerSupabaseClient } from "@/lib/supabase/server";

type Supabase = Awaited<ReturnType<typeof createServerSupabaseClient>>;

function pricesDb(supabase: Supabase) {
  return supabase as unknown as {
    from: (table: "product_prices") => ReturnType<Supabase["from"]>;
  };
}

export async function upsertRetailPrice(
  supabase: Supabase,
  productId: string,
  price: number,
  options?: { autoGenerated?: boolean }
): Promise<void> {
  const autoGenerated = options?.autoGenerated ?? false;
  const { data: row } = await pricesDb(supabase)
    .from("product_prices")
    .select("id")
    .eq("product_id", productId)
    .eq("price_type", "retail")
    .is("effective_to", null)
    .order("effective_from", { ascending: false })
    .limit(1)
    .maybeSingle();
  if (row?.id) {
    const { error } = await pricesDb(supabase)
      .from("product_prices")
      .update({ price, auto_generated: autoGenerated })
      .eq("id", row.id);
    if (error) throw new Error(error.message);
  } else {
    const { error } = await pricesDb(supabase).from("product_prices").insert({
      product_id: productId,
      price_type: "retail",
      price,
      min_qty: 1,
      auto_generated: autoGenerated,
    });
    if (error) throw new Error(error.message);
  }

  await syncBaseUnitRetailPrice(supabase, productId, price);
}
